/**
 * SpaceGen Racing — WHICH ART EXISTS.
 * ---------------------------------------------------------------------------
 * GENERATED by tools/import-art.mjs from the files in public/. Do not edit by
 * hand: run `node tools/import-art.mjs --src=<folder>` to add art, and the
 * tool rewrites this list from what is actually on disk.
 *
 * An id here has `public/<kind>/<id>-<size>.webp` at every size in ART_SIZES.
 * An id NOT here has no art yet and is drawn as its stand-in, which is how a
 * roster can be twenty-three portraits and one placeholder without a broken
 * image anywhere. tests/art.test.ts holds this list to the folder.
 */

/** Square edge lengths, in pixels, that every art file is exported at. */
export const ART_SIZES = [128, 256, 512] as const

export type ArtSize = typeof ART_SIZES[number]

/** Avatar ids with art in public/avatars/. */
export const AVATAR_ART: readonly string[] = [
  'apexrunner',
  'cadet',
  'dockhand',
  'emberhand',
  'ferrypilot',
  'flagbearer',
  'frostwarden',
  'halfmillion',
  'hollowcantor',
  'ironrun',
  'laurel',
  'linekeeper',
  'marshal',
  'nomad',
  'oldguard',
  'pacer',
  'scrapjack',
  'singularity',
  'stormwright',
  'tidecaller',
  'veteran',
  'voidsmith',
  'wrench',
]

/** Badge ids with art in public/badges/. */
export const BADGE_ART: readonly string[] = [
  'comeback',
  'finishes',
  'frontrunner',
  'full-garage',
  'grand-champion',
  'iron-will',
  'knockouts',
  'legendary-drifts',
  'perfectionist',
  'rocket-start',
  'sharpshooter',
  'track-cleanlap',
  'track-driftking',
  'track-holeshot',
  'track-laprecord',
  'track-perfect',
  'track-summit',
  'track-victory',
  'track-wrecking',
  'untouchable',
  'wins',
  'world-tour',
]
